### PR TITLE
Cleanup conf

### PR DESCRIPTION
**Pull request by dlyr**
UPDATE the form below to describe your PR.

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Change the pre commit script to non interactive. Interactive script have issue with git gui or other ide.
The script format and stage the modified section of the commit. If modifications are detected, it stops the commit operation so you can inspect before commit again.

I also cleanup gitignore file, since we are compiling out of source tree, and we want resources files to be available on git status (at least I do).

### CODE REVIEW

**Comment by nmellado** [comment]
Please do not change the cmakefiles to avoid conflict with the other PRs.

**Comment by MathiasPaulin** [comment]
> Please do not change the cmakefiles to avoid conflict with the other PRs.

But this must be done to have .gitignore clean.

**Comment by nmellado** [comment]
Ok then, I’ll handle it.

**Comment by MathiasPaulin** [comment]
Need only to insert this 2 lines on top of the toplevel cmakefile. (the `project` command is on the 1st line and these must be set before).

**Comment by nmellado** [comment]
> before).

@MathiasPaulin this change has unwanted side effects, I suggest to revert them and accept the PR as it was.

**Comment by dlyr** [comment]
@MathiasPaulin could you update/finish/accept your review ?

**Comment by dlyr** [comment]
@mathiaspaulin could you accept the PR ?

**Pull request merged**
