### PR TITLE
fix multiple resources directories issue (#946)

### LINKED ISSUE #946: Missing resources when installing library with multiple resources directories
When installing a plugin which depends on an helper libs having multiple resources directories, only the last declared resource dir is installed alongside the plugin.
This is related on how the resource installation and registration is performed in RadiumSetupfunctions.cmake. 
Right now, only one resource dir is associated with a target.
Associating several resource directories to a target (library, plugin or application) can help developers in their resource management.

### PR DESCRIPTION
**Pull request by MathiasPaulin**
closes #946 

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Allows to manage several resources directories per Radium artifact (library, plugin, application)

* **What is the current behavior?** (You can also link to an open issue here)

When a library with several resources directories declared (using the radium-cmake function install_target_resources), only the last declared is installed if this library is used as an helper-lib for a plugin or a dependency for other installable artifact.

* **What is the new behavior (if this is a feature change)?**
A target store a list of associated resource directories instead of only one directory

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

no

* **Other information**:

### CODE REVIEW

**Comment by MathiasPaulin** [comment]
> Before going deeper in the review, this mechanism works fine with shared libs and apps right ? 

Only tested with share libs and plugins (see below). All the apps I have were not impacted by the bug. If you have one, I'll do the tests.

> Could this PR take benefit of install_target_resources as done in e.g. configure_cmdline_radium_app ?

I'm not sure to understand your question as this PR modify install_target_resources function to fix the resource installation problem. 

Bellow a use case that allows us to identify the bug and to correct it.

Given a library, say `TheLibrary`, configured as 
```
find_package(Radium REQUIRED Engine)
...
target_link_libraries(
        ${PROJECT_NAME}
        PUBLIC
        Radium::Engine
)

configure_radium_library(
        TARGET ${PROJECT_NAME}
        TARGET_DIR ${PROJECT_NAME}
        PACKAGE_DIR ${CMAKE_INSTALL_PREFIX}/lib/cmake
        NAMESPACE ${PROJECT_NAME}
        FILES "${public_headers};${public_inlines}"
)
configure_radium_package(
    NAME ${PROJECT_NAME}
    PACKAGE_DIR ${CMAKE_INSTALL_PREFIX}/lib/cmake
    PACKAGE_CONFIG ${CMAKE_CURRENT_SOURCE_DIR}/Config.cmake.in
    PACKAGE_VERSION ${PROJECT_VERSION}
)

install_target_resources(
        TARGET ${PROJECT_NAME}
        RESOURCES_INSTALL_DIR ${PROJECT_NAME}
        RESOURCES_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Shaders
)

install_target_resources(
        TARGET ${PROJECT_NAME}
        RESOURCES_INSTALL_DIR ${PROJECT_NAME}
        RESOURCES_DIR ${CMAKE_CURRENT_SOURCE_DIR}/MetaData
)

```

When installing this library, the two resources directories are installed in the right place. This was true before this PR and still true after.

Now, consider a plugin configured by 
```
find_package(Radium REQUIRED COMPONENTS PluginBase)
find_package(TheLibrary REQUIRED)

...
 target_link_libraries(
        ThePlugin
        Radium::PluginBase
        TheLibrary
    )

configure_radium_plugin(
        NAME ThePlugin
        HELPER_LIBS TheLibrary
        INSTALL_IN_RADIUM_BUNDLE
)

```

When installing this plugin (here in the Radium bundle), it is expected that the helper library `TheLibrary` (the .so or .dylib) and its resource (here, Shaders and MetaData) are copied in the directory of the plugin, (Radium-Bundle/Plugins/lib for the .so, Radium-Bundle/Plugins/Resources/TheLibrary/xxx for the resources directories xxx). 
This is the way plugins are installed and this worked fine before this PR if the library requires only one resource directory. 
But before this PR, in the above example, only the last registered resource directory (MetaData) was copied in the Plugin directory. 
This PR fix this and make all the resources directories to be copied at the right place.
This was tested with a library you have access to (libGltf - branch release-candidate) that can be included in all the Radium applications through a simple plugin or linked directly for applications that do not support plugins. 
Both usage works now. 
But I've not tested to install bundled application not relying on plugins to use this library. 
For installed bundled applications that rely on plugins to use this library, all works fine (on macos).

**Comment by MathiasPaulin** [comment]
And, I forgot, resources associated with an app are installed with the app. So, there were no problems with app resources neither before this PR, neither after.

**Comment by dlyr** [comment]
Maybe I still miss something, but I exepect `configure_radium_plugin` to call `install_target_resources`, as `configure_radium_app` do. Which do not seems to be the case. But maybe the question is out of the PR scope.

**Review by dlyr — APPROVED** [review]

**Review by nmellado — APPROVED** [review]

**Comment by MathiasPaulin** [comment]
> Maybe I still miss something, but I exepect `configure_radium_plugin` to call `install_target_resources`, as `configure_radium_app` do. Which do not seems to be the case. But maybe the question is out of the PR scope.

You're right, you miss something : the problem is not with the resources associated with the plugin, that are managed - and this PR do nothing for this as it works well -  exactly as you expect,  but with the resources of the **helper libs** of the plugin that are different things.
 In the documentation, helper libs are defined as 
```
HELPER_LIBS Optional. List of libraries (local target or imported targets) the plugin depends on
```
and such library can have its own resources the plugin has not to be aware of.

If needed, I'll clarify this at our new RL meeting.

**Pull request merged**
