### PR TITLE
Code style refactoring

### PR DESCRIPTION
**Pull request by nmellado**
* **Please check if the PR fulfills these requirements**
- [x] Is the Pull-Request done against the right branch:
  - `master`: for hotfixes not impacting the API
  - `master-v1`: for changes related to the Radium Stable Release V1.
- [x] The commit message follows our guidelines
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] Tests for the changes have been added (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR aims at defining the new Radium’s filesystem, namespaces and code style + change introduces some changes in Radium's Core to help further developments.
Added features : 
 - Code formatting: clang-format config file, some script and pre commit hook (for linux)
 - Continuous Integration: stability improvements
 - Refactor lights and material management 

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
Add pre commit hook script that compares files to be commited to clang-formated versions, it proposes to apply a patch if it differs.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Yes. It will break Radium’s API
Will fix:  #178

* **Other information**:
No other PR can be accepted on master-v1 before this one.

### CODE REVIEW

**Comment by nmellado** [comment]
Feel free to add commit to this PR:
 - optimize include directives, 
 - synchronize namespace and filesystem,
 - update namespaces,
 - update filesystem.

**Comment by MathiasPaulin** [comment]
When removing superfluous virtual for inherited method (marked as override). I reach to some untaken decision : what about inherited destructors.
According to clang-tidy, inherited destructors must be marked as override and not as virtual.
According to [Bjarne Stroustrup and Herb Sutter](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c-core-guidelines), 
[If a base class destructor is declared virtual, one should avoid declaring derived class destructors virtual or override.](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final)
What de we decide ?

**Comment by dlyr** [comment]
Of course follow Bjarne advice !

**Comment by MathiasPaulin** [comment]
Well ... why do not put a .clang-format configuration file on radium root dir instead of using a separate scripts dir that will be usable only under Linux ? Doing that, clang-format will be able to locate easily its parameters. Seen in the doc of clang-format : 
```
Use -style=file to load style configuration from
                              .clang-format file located in one of the parent
                              directories of the source file (or current
                              directory for stdin).
```
Most modern IDE are able to call ```clang-format --style=file``` on file save ...

**Comment by dlyr** [comment]
The doc say 
```
Please follow the scripts/clang-format coding style (tested `with clang-format 6.0`)
To use it, you have to copy or link `sciprts/clang-format` to `.clang-format` (in Radium-Engine root dir).
```
The script just do the copy for you, but I found usefull to have the radium version in the script dir and let git ignore about config "." files. Specially if some option of the radium version is not compatible with client version of clang-format.

**Comment by MathiasPaulin** [comment]
Well, my last commit was done in two times. The real refactoring and the code formating with clang-format. This is because the ```scripts/format-all.sh```script  contains the name of clang-format as on Debian Linux install (```clang-format-6.0```). On my machine, the real executable is ```clang-format-mp-6.0``` accessible with ```clang-format``` thanks to a link set with the equibvalent of ```update alternatives ```. I'll try to make the detection of ```clang-format*-6.0``` robust through different installs ...
Sorry for the commit noise ...

**Pull request merged**
