### PR TITLE
Add compiler version verification at configure time.

### LINKED ISSUE #664: Use of filesystem::lexically_normal not available in experimental
Current version of `master` requires cxx_17 capabilities at this line: 
https://github.com/STORM-IRIT/Radium-Engine/blob/31523ca27aaa231751b9dff4e2c4343225ee2c00/src/Core/Resources/Resources.cpp#L31

Doc: https://en.cppreference.com/w/cpp/filesystem/path/lexically_normal

As such, some compilers (e.g., gcc-7) cannot compile radium.

### PR DESCRIPTION
**Pull request by MathiasPaulin**
closes #664
This PR add compiler version verification for Radium bundle at configure time. 
This verification is exported to any Radium based system and is automatically done when `find_package(Radium)` is executed.

_Check if you branch history is PR compatible_
- Your branch need to be up to date with origin/master AND to have linear history (i.e. no merge commit).
- Update your git repository `git fetch origin` if origin is this remote
- Check with the script provided in `scripts/is-history-pr-compatible.sh`
- You must use clang-format style
_These checks are enforced by github workflow actions_
_Please refer to the corresponding log in case of failure_

_UPDATE the form below to describe your PR._

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Verify that the compiler used for compiling Radium or on of its client (plugin, lib, app) is conform to the requirements

* **What is the current behavior?** (You can also link to an open issue here)

No compiler version is verified

* **What is the new behavior (if this is a feature change)?**
* 
Stop at configure time if the compiler version does not meet the requirements

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
Solution taken from there : https://stackoverflow.com/questions/14933172/how-can-i-add-a-minimum-compiler-version-requisite

do we have to implement more complex testing (i.e. feature-detection approach) ?

### CODE REVIEW

**Comment by MathiasPaulin** [comment]
I found two concerns with the way I implement compiler version verification. 
 - It is done at two different places (general CMakeLists.txt and package configuration file)
 - The required version are encoded twice also.

**Comment by nmellado** [comment]
In order to avoid duplication, could you move the verification code in a macro (accessible both at build time and in the package) ?
Also, the version number for VS is very very accurate, maybe we can skip the minor version check ?

**Comment by nmellado** [comment]
> > In order to avoid duplication, could you move the verification code in a macro (accessible both at build time and in the package) ?
> 
> I prefer functions instead of macro but then, the function must be called explicitely and the included file installed with Radium as for `radium_setup_functions`
Don’t mind between macro and functions, but you get my point. And yes, this should be made available in the installed package.


> 
> > Also, the version number for VS is very very accurate, maybe we can skip the minor version check ?
> 
> need to test this. I took the version numbers from the doc.
Ok. Skipping minor is probably ok then, as supported features change with major compiler versions.

**Comment by MathiasPaulin** [comment]
Supported compilers are defined only once without installing one more file. 
Using this solution, we can remove the need to install `radium_setup_functions.cmake` by embeding it into the `RadiumConfig.cmake`. This might prevent misusage of this include script.

**Review by nmellado — APPROVED** [review]

**Pull request merged**
