### PR TITLE
Test new style customisation ...

### PR DESCRIPTION
**Pull request by dlyr**
* **Please check if the PR fulfills these requirements**
- [x] Is the Pull-Request done against the right branch:
  - `master`: for hotfixes not impacting the API
  - `master-v1`: for changes related to the Radium Stable Release V1.
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
conding style only, give it a try (you can checkout script/clang-format file only if you want)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by dlyr** [comment]
BTW, to amend some conf stuff, please do this way:
1. Apply format to you code,
2. Find one ugly piece of code (you can just post a comment at this step referencing the file/line so we can discuss)
3. Check clang-format doc [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
4. Find if an option could resolve your problem
5. Test it and commit
Please do not check every possible options and set them without aiming at correcting a ugly piece of code, as the base style do a lot !

**Comment by nmellado** [comment]
It's been a while we use the same style on `master-v1`, and nobody seems to complain about it anymore.
I'm wondering if we still need this PR.
Any comment ?

**Comment by MathiasPaulin** [comment]
Well, I integrated ths style in one of my external project and, if a agree (and enjoy) most of what is proposed, I have some questions and remarks.
It seems that small if/else block is systematically transformed in one line if the limit of 100 chars is not reached. This results in a lot of if/else blocks where each branch stay in 1 instruction being formatted in 4 lignes for the if part (if, {, code, })  and 1 for the else  part ( else{code}). Not so aesthetic afterthat ...

When dealing with Eigen matrices and initialization of matrices, it easier to read : 
```
matrix << m00, m01, m02, m03,
          m10, m11, m12, m13, 
          m20, m21, m22, m23,
          m30, m31, m32, m33;
```
than
```
matrix << m00, m01, m02, m03, m10, m11, m12, m13,  m20, m21, m22, m23, m30, m31, m32, m33;
```
But the formatter always rearrange this kind of writing.
I've not found how to limit this.

Nevertheless, OK to integrate the .clang-format of this PR into master-v1. This will generates a commit modifying all the radium files. Beware of merge conflicts with our own branchs afterthat ...

**Comment by dlyr** [comment]
For the matrix issue, you can add comment marks at line break
```c++
matrix << m00, m01, m02, m03, //
    m10, m11, m12, m13,       //
    m20, m21, m22, m23,       //
    m30, m31, m32, m33;
```
But I had no clue on how to align the second line with the first. A more intrusive solution is to 
```c++
// clang-format off
matrix << m00, m01, m02, m03,
          m10, m11, m12, m13,
          m20, m21, m22, m23,
          m30, m31, m32, m33;
// clang-format on
```
But that's a step toward evil practices.

Could you post an example of `if else` that do not fit your expectations. I think the behavior for the single blocked else is a bug ...
With nothing more than `BeforeElse: true` I have 

```c++
if ( true ) {
    i++;
}
else {
    i--;
}
```
and if I add `  AfterControlStatement: true`, I have 
```c++
if ( true )
{
    i++;
}
else
{ i--; }
```

**Comment by dlyr** [comment]
And I propose to intergrate the format just before releasing v1 ;)

**Comment by dlyr** [comment]
And regarding @nmellado comment, this branch clang-format is for me the one to use for next release. The one in master-v1 has some drawbacks, so we need to merge before closing the PR.

**Comment by nmellado** [comment]
Ok great thanks.
As planned this will be the latest PR merged before releasing Radium v1.

**Comment by nmellado** [comment]
Done in 11cb445 
Closing

**Pull request closed without merging**
