### PR TITLE
fix SimpleAnim w.r.t. time management in RadiumEngine

### PR DESCRIPTION
**Pull request by hoshiryu**
UPDATE the form below to describe your PR.

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Configure the RadiumEngine so that it is the one managing time

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by nmellado** [comment]
Thanks, please update according to `master` (note that all files have been reformatted, that you need to preformat your code before re-applying your changes).

**Comment by nmellado** [comment]
@dlyr can you describe somehow how to get the linear history to @hoshiryu ?

**Comment by nmellado** [comment]
For this PR I think that both squash or rebase are ok (squash is easier)

**Comment by dlyr** [comment]
easiest way, if clang format 9 and under linux, call `./scripts/format-all.sh` or check [wiki](https://github.com/STORM-IRIT/Radium-Engine/wiki/Rebase-on-reformatted-master)

**Comment by hoshiryu** [comment]
well, I don't have this version...

**Comment by dlyr** [comment]
but it seems to be fixed

**Pull request merged**
