### PR TITLE
Fix issue Crash on reset scene #314

### PR DESCRIPTION
**Pull request by MathiasPaulin**
* **Please check if the PR fulfills these requirements**
- [x] Is the Pull-Request done against the right branch:
  - `master-v1`: for changes related to the Radium Stable Release V1.
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix of issue Crash on reset scene #314

* **What is the current behavior?** (You can also link to an open issue here)
When clearing the scene, the headlight entity is deleted and so the headlight component. The application the crashed when using this already stored and used component.

* **What is the new behavior (if this is a feature change)?**
HeadLight is added as a component of the System Entity instead of as a component of its own entity. This prevents the deletion of the headlight component.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by hoshiryu** [comment]
Ok for me, checked on Linux

**Comment by nmellado** [comment]
Waiting for CI + need update from base branch.

**Comment by MathiasPaulin** [comment]
@nmellado OK, tested, all is fine for me, we can approve this PR as soon as the CI finished.

**Comment by nmellado** [comment]
Closes #314

**Pull request merged**
