### PR TITLE
Todos doc and comment.

### PR DESCRIPTION
**Pull request by dlyr**
Fixes some of the forgotten review of #476

### CODE REVIEW

**Comment by nmellado** [comment]
Great thanks @dlyr 
@hoshiryu are all your recommended changes included ?

**Comment by MathiasPaulin** [comment]
> We still do not agree with @MathiasPaulin about the OpenGL error check (can raise `GL_INVALID_OPERATION`).
Which and why ?

**Comment by hoshiryu** [comment]
Just a question @MathiasPaulin why is there a `Material` in a `RenderObject` since we have it as the `ShaderParameterProvider` of the `RenderTechnique` ?

**Comment by MathiasPaulin** [comment]
> Just a question @MathiasPaulin why is there a `Material` in a `RenderObject` since we have it as the `ShaderParameterProvider` of the `RenderTechnique` ?

Because nothing says that only materials could be `ShaderParameterProvider`. 
We can define rendertechnique (we have some on our renderers) that need a much more advanced `ShaderParameterProvider` than materials but that still use the material for defining a subset of its parameter. Materials is a BSDF calculator. If we need to compute the appearance of an object in a different way, we migh create RenderTechnique with `ShaderParameterProvider` that is not a meterial.

**Comment by hoshiryu** [comment]
> > We still do not agree with @MathiasPaulin about the OpenGL error check (can raise `GL_INVALID_OPERATION`).
> > Which and why ?

ok I was looking to an older version's doc, my mistake

**Comment by hoshiryu** [comment]
> > Just a question @MathiasPaulin why is there a `Material` in a `RenderObject` since we have it as the `ShaderParameterProvider` of the `RenderTechnique` ?
> 
> Because nothing says that only materials could be `ShaderParameterProvider`.
> We can define rendertechnique (we have some on our renderers) that need a much more advanced `ShaderParameterProvider` than materials but that still use the material for defining a subset of its parameter. Materials is a BSDF calculator. If we need to compute the appearance of an object in a different way, we migh create RenderTechnique with `ShaderParameterProvider` that is not a meterial.

Then what's the better way to change the `Material` if we don't know what's in there? Through the `RenderObject` or the `RenderTechnique`?

**Comment by MathiasPaulin** [comment]
> > > We still do not agree with @MathiasPaulin about the OpenGL error check (can raise `GL_INVALID_OPERATION`).
> > > Which and why ?
> 
> ok I was looking to an older version's doc, my mistake

FYI : https://www.khronos.org/registry/OpenGL-Refpages/gl4/

**Comment by MathiasPaulin** [comment]
> > > Just a question @MathiasPaulin why is there a `Material` in a `RenderObject` since we have it as the `ShaderParameterProvider` of the `RenderTechnique` ?
> > 
> > 
> > Because nothing says that only materials could be `ShaderParameterProvider`.
> > We can define rendertechnique (we have some on our renderers) that need a much more advanced `ShaderParameterProvider` than materials but that still use the material for defining a subset of its parameter. Materials is a BSDF calculator. If we need to compute the appearance of an object in a different way, we migh create RenderTechnique with `ShaderParameterProvider` that is not a meterial.
> 
> Then what's the better way to change the `Material` if we don't know what's in there? Through the `RenderObject` or the `RenderTechnique`?

The `RenderTechnique` has no knowledge of any material! They know only `ShaderParameterProvider`.
So, you have your answer.

But remember, it is the renderer that know how to consgtruct the rendertechnique he needs. So, if you change the material, you have to ask the renderer to build the renderTechnique for the RenderObject through a call to the method `Renderer::buildRenderTechnique( RenderObject* ro )`

**Comment by nmellado** [comment]
@MathiasPaulin are you fine with the changes ?

**Comment by nmellado** [comment]
@hoshiryu are you fine with these changes (please update your review accordingly)

**Comment by hoshiryu** [comment]
already up to date

**Comment by nmellado** [comment]
@MathiasPaulin / @dlyr  can you answer @hoshiryu comments please ?

**Pull request merged**
