### PR TITLE
Material openGL state could be forced to be updated

### PR DESCRIPTION
**Pull request by MathiasPaulin**
...  from any software part.

This will allow to fix issue https://github.com/STORM-IRIT/Radium-Apps/issues/12

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR allow applications or components to ask for OpenGL state update on Materials.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by MathiasPaulin** [comment]
> Couldn't we use the observable pattern here ?
> > ask for link to observable first

what do you mean by these ?

**Comment by nmellado** [comment]
You added a `dirty` flag, this is something we did for other object, I was wondering if some code couldn't be factorized.
One option could be to have an observer of the material, that is triggered each time the Material is modified. This would replace the dirty flag. 
@dlyr  do you follow me ?

**Comment by MathiasPaulin** [comment]
Well, the dirty flag was already here. I add nothing else than a mean to modify it from a non Material-derived class.
If we want to edit materials, and want the editor to be general enough to handle any material implementing the Material interface, there is a lot of work to do and, yes, the Oservable pattern will be helpful. 
But for now, the objective of this PR is far less ambitious. It is just to remove a regression on the Radium apps (main-app). (see the corresponding PR on Radium-Apps : https://github.com/STORM-IRIT/Radium-Apps/pull/13)

**Comment by nmellado** [comment]
Ok.
Waiting for CI before merging

**Comment by dlyr** [comment]
I though I have commented. Anyway.
The idea here is that all material setters should call this function.
But in the current state, material class data members are public, so it's not possible to watch their modification.
\todo : add setters, call needUpdate (I'll create an quick issue on this to have a reminder)
So fine for approval.

**Pull request merged**
