### PR TITLE
Small setting editor available for BaseApplication derived applications.

### PR DESCRIPTION
**Pull request by MathiasPaulin**
This add a "Setting editor" to any BaseApplication derived apps.
This PR is far for being ready to review but define a first, minimalistic setting editor.

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] Tests for the changes have been added (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by nmellado** [comment]
This PR is very old. Does it make sense to keep it open ? Should we move it as an issue or a discussion ?

From what I see the setting editor would still make sense today. Shall we ask a developer to update/rebase the proposed code against current `master` ?

**Comment by MathiasPaulin** [comment]
> This PR is very old. Does it make sense to keep it open ?

It make sense. I'll rebase on master as, as far as I know, this PR only interact with Gui ...

**Comment by MathiasPaulin** [comment]
The proposal for a setting editor is updated and rebased on the master branch. 
Usage demonstration (and question) is on the PR on Radium-Apps #44 (https://github.com/STORM-IRIT/Radium-Apps/pull/44)
For now, the editor is quite limited and unfriendly but allow to change the path from where is loaded the KeyMappingManager configuration file.

Feel free to test/comment/develop/....

**Review by nmellado — DISMISSED** [review]

**Comment by nmellado** [comment]
For me the code seems to be ready to be merged.

@MathiasPaulin in your initial PR description you were mentioning:

> Several problems must be solved before integrating this PR into Radium :
> - Issue #529 that discuss about the Radium Engine UUID. This is related to the name and access of the QSettings file that allow application-based, organization-based or domain-based configuration
>  - Settings organization as there are some inconsistancy in the management of keymapping/config files and the way they are loaded ...
>  - The need for persistant settings ...

Are these comments still up to date ? Shall we move them in dedicated issues ?

**Review by dlyr — DISMISSED** [review]
I'm fine with the PR (and with the new style, "ça claque" more or less ...)
But I don't get why the help button since the signal is not catch ...
Moreover it can be a good idea to have settings "reset to default" and a ligne by possible settings (here only modified settings are shown, e.g. background color)
Last, settings edits are not applied on the fly, only at startup, I don't know how easy is to link settings editor to the corresponding slot in the application.
Nevertheless, the PR could be accepted as is,

**Comment by nmellado** [comment]
Fine for me as well (need rebase on top of `master`.

**Comment by MathiasPaulin** [comment]
> I'm fine with the PR (and with the new style, "ça claque" more or less ...)
> But I don't get why the help button since the signal is not catch ...

This let the application to define its own help. 

> Moreover it can be a good idea to have settings "reset to default" and a ligne by possible settings (here only modified settings are shown, e.g. background color)

I agree.

> Last, settings edits are not applied on the fly, only at startup, I don't know how easy is to link settings editor to the corresponding slot in the application.

I'll search how to do that

> Nevertheless, the PR could be accepted as is,

I don't think so. Some "style" question should be resolved before that (see the PR to come)

**Comment by nmellado** [comment]
I agree with @MathiasPaulin that we should not have a custom style for a given window: style must be defined at the application level for better consistency.
Also, we need to be sure that a style is supported on all operating systems (e.g. fonts).

**Review by nmellado — CHANGES_REQUESTED** [review]
Commit 6209d19 introduce non portable look and field.
Please reset to default.

**Comment by MathiasPaulin** [comment]
Closed as this. Will be splitted in 2.

**Pull request closed without merging**
