### PR TITLE
Engine reorganize directory structure

### PR DESCRIPTION
**Pull request by dlyr**
First tentative to reorganize source files in src/Engine
Most of the changes are scripted, so upcomming comments are "easy" to account for.
When ready, I'll rewrite history, and release the script for include renaming (for third party applications and plugins).

### CODE REVIEW

**Comment by dlyr** [comment]
New file structure 

```
Engine/Component
Engine/Component/Component.cpp
Engine/Component/Component.hpp
Engine/Component/Component.inl
Engine/Component/GeometryComponent.cpp
Engine/Component/GeometryComponent.hpp
Engine/Component/GeometryComponent.inl
Engine/Entity
Engine/Entity/Entity.cpp
Engine/Entity/Entity.hpp
Engine/Entity/Entity.inl
Engine/FrameInfo.hpp
Engine/ItemModel
Engine/ItemModel/ItemEntry.cpp
Engine/ItemModel/ItemEntry.hpp
Engine/ItemModel/ItemEntry.inl
Engine/Managers
Engine/Managers/CameraManager.cpp
Engine/Managers/CameraManager.hpp
Engine/Managers/CameraStorage.hpp
Engine/Managers/ComponentMessenger.cpp
Engine/Managers/ComponentMessenger.hpp
Engine/Managers/ComponentMessenger.inl
Engine/Managers/DefaultCameraManager.cpp
Engine/Managers/DefaultCameraManager.hpp
Engine/Managers/DefaultLightManager.cpp
Engine/Managers/DefaultLightManager.hpp
Engine/Managers/EntityManager.cpp
Engine/Managers/EntityManager.hpp
Engine/Managers/LightManager.cpp
Engine/Managers/LightManager.hpp
Engine/Managers/LightStorage.hpp
Engine/Managers/SignalManager.cpp
Engine/Managers/SignalManager.hpp
Engine/Managers/SystemDisplay.cpp
Engine/Managers/SystemDisplay.hpp
Engine/RadiumEngine.cpp
Engine/RadiumEngine.hpp
Engine/RaEngine.hpp
Engine/Renderer
Engine/Renderer/BlinnPhongMaterial.cpp
Engine/Renderer/BlinnPhongMaterial.hpp
Engine/Renderer/BlinnPhongMaterial.inl
Engine/Renderer/Camera.cpp
Engine/Renderer/Camera.hpp
Engine/Renderer/Camera.inl
Engine/Renderer/DebugRender.cpp
Engine/Renderer/DebugRender.hpp
Engine/Renderer/DirLight.cpp
Engine/Renderer/DirLight.hpp
Engine/Renderer/DirLight.inl
Engine/Renderer/Displayable
Engine/Renderer/DisplayableObject.hpp
Engine/Renderer/DrawPrimitives.cpp
Engine/Renderer/DrawPrimitives.hpp
Engine/Renderer/ForwardRenderer.cpp
Engine/Renderer/ForwardRenderer.hpp
Engine/Renderer/LambertianMaterial.cpp
Engine/Renderer/LambertianMaterial.hpp
Engine/Renderer/Light.cpp
Engine/Renderer/Light.hpp
Engine/Renderer/Light.inl
Engine/Renderer/MaterialConverters.cpp
Engine/Renderer/MaterialConverters.hpp
Engine/Renderer/Material.cpp
Engine/Renderer/Material.hpp
Engine/Renderer/Material.inl
Engine/Renderer/Mesh.cpp
Engine/Renderer/Mesh.hpp
Engine/Renderer/Mesh.inl
Engine/Renderer/OpenGL.hpp
Engine/Renderer/PlainMaterial.cpp
Engine/Renderer/PlainMaterial.hpp
Engine/Renderer/PointLight.cpp
Engine/Renderer/PointLight.hpp
Engine/Renderer/PointLight.inl
Engine/Renderer/RawShaderMaterial.cpp
Engine/Renderer/RawShaderMaterial.hpp
Engine/Renderer/RawShaderMaterial.inl
Engine/Renderer/Renderer.cpp
Engine/Renderer/Renderer.hpp
Engine/Renderer/RenderObject.cpp
Engine/Renderer/RenderObject.hpp
Engine/Renderer/RenderObjectManager.cpp
Engine/Renderer/RenderObjectManager.hpp
Engine/Renderer/RenderObjectTypes.hpp
Engine/Renderer/RenderParameters.cpp
Engine/Renderer/RenderParameters.hpp
Engine/Renderer/RenderParameters.inl
Engine/Renderer/RenderTechnique.cpp
Engine/Renderer/RenderTechnique.hpp
Engine/Renderer/RenderTechnique.inl
Engine/Renderer/ShaderConfigFactory.cpp
Engine/Renderer/ShaderConfigFactory.hpp
Engine/Renderer/ShaderConfiguration.cpp
Engine/Renderer/ShaderConfiguration.hpp
Engine/Renderer/ShaderProgram.cpp
Engine/Renderer/ShaderProgram.hpp
Engine/Renderer/ShaderProgram.inl
Engine/Renderer/ShaderProgramManager.cpp
Engine/Renderer/ShaderProgramManager.hpp
Engine/Renderer/SimpleMaterial.cpp
Engine/Renderer/SimpleMaterial.hpp
Engine/Renderer/SimpleMaterial.inl
Engine/Renderer/SpotLight.cpp
Engine/Renderer/SpotLight.hpp
Engine/Renderer/SpotLight.inl
Engine/Renderer/Texture.cpp
Engine/Renderer/Texture.hpp
Engine/Renderer/TextureManager.cpp
Engine/Renderer/TextureManager.hpp
Engine/Renderer/ViewingParameters.hpp
Engine/Renderer/VolumeObject.cpp
Engine/Renderer/VolumeObject.hpp
Engine/Renderer/VolumeObject.inl
Engine/Renderer/VolumetricMaterial.cpp
Engine/Renderer/VolumetricMaterial.hpp
Engine/Renderer/VolumetricMaterial.inl
Engine/System
Engine/System/CouplingSystem.hpp
Engine/System/GeometrySystem.cpp
Engine/System/GeometrySystem.hpp
Engine/System/System.cpp
Engine/System/System.hpp
```

**Comment by MathiasPaulin** [comment]
I found it is a good idea to simplify the directories structure of the Engine Classes. 
But I do not fully agree with the proposed one, mainly for the `Renderer` directory that seems to be rather a tote bag than a structuration tool.

I suggest, in a first time, to define the following directory structure for the Engine (not in alphabetical order here to exhibit some sementic) : 
```
Engine/
Engine/Entity 
Engine/Component 
Engine/System 
Engine/Messaging

Engine/Shaders
Engine/Camera 
Engine/Light 
Engine/Displayable 
Engine/Material
Engine/Texture 

Engine/Renderer 
```

and to populate this structure as the following

```
# main entry point to use the Engine
Engine/RadiumEngine.cpp
Engine/RadiumEngine.hpp
Engine/RaEngine.hpp
Engine/OpenGL.hpp

# Entity related classes
Engine/Entity
Engine/Entity/Entity.cpp
Engine/Entity/Entity.hpp
Engine/Entity/Entity.inl
Engine/Entity/EntityManager.cpp
Engine/Entity/EntityManager.hpp
Engine/Entity/SystemDisplay.cpp
Engine/Entity/SystemDisplay.hpp # Part of this file might be moved to Component

# Component related classes
Engine/Component  
Engine/Component/Component.cpp
Engine/Component/Component.hpp
Engine/Component/Component.inl
Engine/Component/GeometryComponent.cpp
Engine/Component/GeometryComponent.hpp # Might be split into several files
Engine/Component/GeometryComponent.inl

# System related classes
Engine/System
Engine/System/FrameInfo.hpp
Engine/System/CouplingSystem.hpp
Engine/System/GeometrySystem.cpp
Engine/System/GeometrySystem.hpp
Engine/System/System.cpp
Engine/System/System.hpp
# Even if named as "manager", this is a system to handle the Cameras
Engine/System/CameraManager.cpp
Engine/System/CameraManager.hpp
Engine/System/CameraStorage.hpp
Engine/System/DefaultCameraManager.cpp
Engine/System/DefaultCameraManager.hpp
# Even if named as "manager", this is a systems to handle the Lights
Engine/System/DefaultLightManager.cpp
Engine/System/DefaultLightManager.hpp
Engine/System/LightManager.cpp
Engine/System/LightManager.hpp
Engine/System/LightStorage.hpp

# Communication classes
Engine/Messaging/ComponentMessenger.cpp
Engine/Messaging/ComponentMessenger.hpp
Engine/Messaging/ComponentMessenger.inl
Engine/Messaging/SignalManager.cpp
Engine/Messaging/SignalManager.hpp
Engine/Messaging/ItemEntry.cpp
Engine/Messaging/ItemEntry.hpp
Engine/Messaging/ItemEntry.inl


# Shaders and Program 
Engine/Shaders
Engine/Shaders/RenderParameters.cpp
Engine/Shaders/RenderParameters.hpp
Engine/Shaders/RenderParameters.inl
Engine/Shaders/ShaderConfigFactory.cpp
Engine/Shaders/ShaderConfigFactory.hpp
Engine/Shaders/ShaderConfiguration.cpp
Engine/Shaders/ShaderConfiguration.hpp
Engine/Shaders/ShaderProgram.cpp
Engine/Shaders/ShaderProgram.hpp
Engine/Shaders/ShaderProgram.inl
Engine/Shaders/ShaderProgramManager.cpp
Engine/Shaders/ShaderProgramManager.hpp

# Cameras 
Engine/Camera 
Engine/Camera/Camera.cpp
Engine/Camera/Camera.hpp
Engine/Camera/Camera.inl
Engine/Camera/ViewingParameters.hpp

# Lights 
Engine/Light
Engine/Light/DirLight.cpp
Engine/Light/DirLight.hpp
Engine/Light/DirLight.inl
Engine/Light/Light.cpp
Engine/Light/Light.hpp
Engine/Light/Light.inl
Engine/Light/PointLight.cpp
Engine/Light/PointLight.hpp
Engine/Light/PointLight.inl
Engine/Light/SpotLight.cpp
Engine/Light/SpotLight.hpp
Engine/Light/SpotLight.inl

# Displayable elements
Engine/Displayable 
Engine/Displayable/Displayable
Engine/Displayable/DisplayableObject.hpp
Engine/Displayable/DrawPrimitives.cpp
Engine/Displayable/DrawPrimitives.hpp
Engine/Displayable/VolumeObject.cpp
Engine/Displayable/VolumeObject.hpp
Engine/Displayable/VolumeObject.inl
Engine/Displayable/Mesh.cpp
Engine/Displayable/Mesh.hpp
Engine/Displayable/Mesh.inl

# Materials and appearance management 
Engine/Material
Engine/Material/BlinnPhongMaterial.cpp
Engine/Material/BlinnPhongMaterial.hpp
Engine/Material/BlinnPhongMaterial.inl
Engine/Material/LambertianMaterial.cpp
Engine/Material/LambertianMaterial.hpp
Engine/Material/Material.cpp
Engine/Material/Material.hpp
Engine/Material/Material.inl
Engine/Material/MaterialConverters.cpp
Engine/Material/MaterialConverters.hpp
Engine/Material/PlainMaterial.cpp
Engine/Material/PlainMaterial.hpp
Engine/Material/RawShaderMaterial.cpp
Engine/Material/RawShaderMaterial.hpp
Engine/Material/RawShaderMaterial.inl
Engine/Material/SimpleMaterial.cpp
Engine/Material/SimpleMaterial.hpp
Engine/Material/SimpleMaterial.inl
Engine/Material/VolumetricMaterial.cpp
Engine/Material/VolumetricMaterial.hpp
Engine/Material/VolumetricMaterial.inl

# Textures & Images
Engine/Texture 
Engine/Texture/Texture.cpp
Engine/Texture/Texture.hpp
Engine/Texture/TextureManager.cpp
Engine/Texture/TextureManager.hpp


# Renderers and rendering
Engine/Renderer
Engine/Renderer/DebugRender.cpp
Engine/Renderer/DebugRender.hpp
Engine/Renderer/ForwardRenderer.cpp
Engine/Renderer/ForwardRenderer.hpp
Engine/Renderer/Renderer.cpp
Engine/Renderer/Renderer.hpp
Engine/Renderer/RenderObject.cpp
Engine/Renderer/RenderObject.hpp
Engine/Renderer/RenderObjectManager.cpp
Engine/Renderer/RenderObjectManager.hpp
Engine/Renderer/RenderObjectTypes.hpp
Engine/Renderer/RenderTechnique.cpp
Engine/Renderer/RenderTechnique.hpp
Engine/Renderer/RenderTechnique.inl

```

Then, starting from this organisation, several classes might be renamed, files might be splitted, documentation might be updated ... so that the Engine classes exhibits some kind of natural structure and meaning ...

**Comment by dlyr** [comment]
Right, 
Let's say a directory is a namespace, and the other way round, except maybe for collection of functions  (like DrawPrimitives)
In the current master we have
```
Engine::
   DrawPrimitives
   EngineMaterialConverters
   EngineRenderTechniques
   ShaderConfigurationFactory
   SurfaceMeshComponentInternal
```
Where the only "real" namespace is Engine, the other are functional namespace.
I'm not sure we need more namespace for engine, but it may be the first answer to find, and to confirm that having directory structures <> namespace is a good way to do (it's what we have done for Core, most of the time).

**Comment by dlyr** [comment]
ping

**Comment by dlyr** [comment]
Quick summary of steering committee 

3 namespaces
Engine::Data: all  low level data representation (or Core data decorate), 
Engine::Scene: Scene graph and scene management : entity, component, links between data, management
Engine::Renderer: Rendering related, main renderer, render technique, render object

Scene needs Data
Renderer needs Data and Scene
(other dependencies should be removed in the futur)

Scene :
Entity → Components → RenderObjects 
                                    → Data

Here are the main moves (directory or files)
```
git mv ./Managers/CameraManager/*              Scene
git mv ./Managers/SignalManager/*                  Scene
git mv ./Managers/EntityManager/*       Scene
git mv ./Managers/ComponentMessenger/*      Scene
git mv ./Managers/SystemDisplay/*        Scene
git mv ./Managers/LightManager/*        Scene
git mv ./Component/*                Scene
git mv ./ItemModel/*                     Scene
git mv ./Entity/*                    Scene
git mv ./System/*                      Scene
git mv ./Renderer/OpenGL/*            .
git mv ./Renderer/Material/*            Data
git mv ./Renderer/Light/*                Data
git mv ./Renderer/Renderers/*              Renderer
git mv ./Renderer/Texture/TextureManager.hpp         Scene
git mv ./Renderer/Texture/TextureManager.cpp         Scene
git mv ./Renderer/Texture/Texture.cpp             Data
git mv ./Renderer/Texture/Texture.hpp             Data
git mv ./Renderer/Mesh/*                        Data
git mv ./Renderer/RenderObject/RenderObjectManager.hpp          Scene
git mv ./Renderer/RenderObject/RenderObjectManager.cpp          Scene 
git mv ./Renderer/RenderObject/RenderObject.cpp             Renderer
git mv ./Renderer/RenderObject/Primitives/*                    Data
git mv ./Renderer/RenderObject/RenderObjectTypes.hpp        Renderer
git mv ./Renderer/RenderObject/RenderObject.hpp            Renderer
git mv ./Renderer/Camera/*                            Data
git mv ./Renderer/Displayable/*                           Data
git mv ./Renderer/RenderTechnique/*                        Renderer
```

**Comment by dlyr** [comment]
Current state, I found a lot of interdependencies between the different namespace
I'll try to make it compile, then we can adapt (for instance component is a base class of some Data classes, Renderer::Shader is needed by Data ... and so on)

Screenshot from 2021-01-21 09-49-42
Screenshot from 2021-01-21 09-49-52
Screenshot from 2021-01-21 09-50-00

**Comment by dlyr** [comment]
After this second round:
 - `Ra::Engine::Renderer::Renderer::*` is not a so nice thing. Which one should we rename, the namespace or the class ?
 -  There is too much dependencies between Data <> Scene and Data <> Renderer.
 -  For instance `Scene::Component` is the base class for `Data::Light` but also `Scene::GeometryComponent` (see below)

The Scene/Data split is not fine for the moment, any proposal welcome.

I propose to move `Data::ViewingParameters` to `Renderer::ViewingParameters` (next commit)

class inheritance

**Comment by dlyr** [comment]
To view dependencies that do not corresponds to our first design (this is simple check, maybe the includes are not needed ...).

Data need Scene and Renderer
```
src/Engine/Data]$ grep Scene * | grep include | cut -f2 -d: | sort | uniq
#include <Engine/Scene/Component.hpp>
#include <Engine/Scene/Entity.hpp>
#include <Engine/Scene/TextureManager.hpp>

src/Engine/Data]$ grep Renderer * | grep include | cut -f2 -d: | sort | uniq
#include <Engine/Renderer/RenderObject.hpp>
#include <Engine/Renderer/RenderParameters.hpp>
#include <Engine/Renderer/RenderTechnique.hpp>
#include <Engine/Renderer/ShaderConfigFactory.hpp>
#include <Engine/Renderer/ShaderProgram.hpp>
#include <Engine/Renderer/ShaderProgramManager.hpp>
```

Scene need Renderer
```
src/Engine/Scene]$ grep Renderer * | grep include | cut -f2 -d: | sort | uniq
#include <Engine/Renderer/RenderObject.hpp>
#include <Engine/Renderer/RenderObjectTypes.hpp>
#include <Engine/Renderer/RenderParameters.hpp>
#include <Engine/Renderer/RenderTechnique.hpp>
```

**Comment by dlyr** [comment]
Well, after checking more in details, I think that:
 

1. The current version of *Light and Camera, since they inherit Component, should be move to Scene namespace.
2. Then we could split these class as a part in Data, handling data storage, and a part in component, handle system communication.
3. We could template LightComponent and CameraComponent with the storage type.

Any thought on that ?

I think the first item can be part of the current PR, 2 and 3 left as future work.

**Comment by nmellado** [comment]
I am fine for step 1. Please create an issue so we don't forget about steps 2 and 3 ;)

**Comment by dlyr** [comment]
I found also that TextureManager can be on the Data side rather than Scene, since it's only used by Data/Materials ...
Comments are welcome to check if every class is in the correct namespace.
(moving one class take around 10 min with the tools I have, to check all includes and fix namespaces)
Also current source might have strages includes or namespace, I have do mostly automatic changes, but not check everything, proof reading needed.

**Comment by MathiasPaulin** [comment]
In some plugins (e.g. SkeletonAnimation) or renderers (e.g. Mara), TextureManager is used to store/access textures from outside of Data/Material. So, I think that this class should remain on the Scene namespace as it manages more than Material attributes.
I'll take a look on your proposal soon to discuss about all suggested changes.

**Comment by dlyr** [comment]
Maybe Material are on the Renderer/Scene side, since they are ShaderParameterProvider more than PureData

**Comment by dlyr** [comment]
Proposal : rename Renderer namespace to Rendering ?

**Comment by dlyr** [comment]
Ok new proposal :
ShaderParameter are Data,
Manager are nearby their managed

Current version is almost fine for the first step

**Comment by nmellado** [comment]
I am fine with the current version.
Refinements will be needed anyway, so I suggest we merge this and fix remaining problems in upcoming PRs.

**Review by nmellado — APPROVED** [review]

**Comment by dlyr** [comment]
Wait until tags, and radium apps are ready

**Pull request merged**
