### PR TITLE
Message format

### PR DESCRIPTION
**Pull request by dlyr**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
cmake message format only

```
Externals will be built with 40 core(s)
-- 
--     == radiumproject Project configuration ==
-- 
-- No CMAKE_BUILD_TYPE, using default CMAKE_BUILD_TYPE=Release
-- USE_GOLD_LINKER                           OFF
-- Found Git: /usr/bin/git (found version "2.28.0") 
Git Changeset: 904ecaf4554303f255d3b826b24ef9cc87f8d90a
-- Can build doc?                            YES
--   + PlantUML - for custom UML             YES 
--   + Graphviz/Dot - for generated graphs   YES 
-- Sanitizers:
--   + ADDRESS_SANITIZER                     OFF
--   + UB_SANITIZER                          OFF
--   + THREAD_SANITIZER                      OFF
-- [addExternalFolder] process Core /my/home/directory/where/i/store/radium/external/Core
-- [addExternalFolder] Create temporary directory
-- [addExternalFolder] Configure cmake project
[addExternalFolder] Skip Core::external update (use RADIUM_SKIP_CORE_EXTERNAL to change behavior)
-- Configuring library Core with standard settings
-- [addExternalFolder] process IO /my/home/directory/where/i/store/radium/external/IO
-- [addExternalFolder] Create temporary directory
-- [addExternalFolder] Configure cmake project with options -DRADIUM_IO_ASSIMP=OFF;-DRADIUM_IO_TINYPLY=ON
[addExternalFolder] Skip IO::external update (use RADIUM_SKIP_IO_EXTERNAL to change behavior)
-- Configuring library IO with standard settings
-- [addExternalFolder] process Engine /my/home/directory/where/i/store/radium/external/Engine
-- [addExternalFolder] Create temporary directory
-- [addExternalFolder] Configure cmake project
[addExternalFolder] Skip Engine::external update (use RADIUM_SKIP_ENGINE_EXTERNAL to change behavior)
-- Configuring library Engine with standard settings
-- [Engine] installing resources from /my/home/directory/where/i/store/radium/Shaders
--  [installTargetResources] Linking resources directory /my/home/directory/where/i/store/radium/Shaders for target Engine into /my/home/directory/where/i/store/radium/build/src/Resources/Shaders
--  [installTargetResources] Installing resources for target Engine into Resources/
-- QT 5.15.1 found.
-- Configuring library GuiBase with standard settings
-- [GuiBase] installing resources from Configs
--  [installTargetResources] Linking resources directory /my/home/directory/where/i/store/radium/src/GuiBase/Configs for target GuiBase into /my/home/directory/where/i/store/radium/build/src/Resources/Configs
--  [installTargetResources] Installing resources for target GuiBase into Resources/
-- QT 5.15.1 found.
-- Configuring library PluginBase with standard settings
-- clang-tidy - static analysis              YES 
-- cppcheck - static analysis                NO 
-- clang-format - code formating             YES 
-- Sanitizers:
--   + ADDRESS_SANITIZER                     OFF
--   + UB_SANITIZER                          OFF
--   + THREAD_SANITIZER                      OFF
-- Already downloaded: https://github.com/catchorg/Catch2.git
--  Configuring application CoreExampleApp for being relocatable after installation.
--  Installing HelloRadium into /my/home/directory/where/i/store/radium/Bundle-GNU
--  Configuring application HelloRadium for being relocatable after installation.
--  Deploying QT is not yet supported for application HelloRadium on Linux
--  Installing SimpleSimulationApp into /my/home/directory/where/i/store/radium/Bundle-GNU
--  Configuring application SimpleSimulationApp for being relocatable after installation.
--  Deploying QT is not yet supported for application SimpleSimulationApp on Linux
--  Installing DrawPrimitivesDemo into /my/home/directory/where/i/store/radium/Bundle-GNU
--  Configuring application DrawPrimitivesDemo for being relocatable after installation.
--  Deploying QT is not yet supported for application DrawPrimitivesDemo on Linux
--  Installing SimpleAnimationApp into /my/home/directory/where/i/store/radium/Bundle-GNU
--  Configuring application SimpleAnimationApp for being relocatable after installation.
--  Deploying QT is not yet supported for application SimpleAnimationApp on Linux
--  Installing plugin demo into /my/home/directory/where/i/store/radium/build/tests/ExamplePluginWithLib/Plugins-GNU
-- 
--     == Final overview for radiumproject ==
-- Version:               1.0.0 beta @ caravage
-- Install prefix:        /my/home/directory/where/i/store/radium/Bundle-GNU
-- Compiler:              /usr/bin/c++
-- CMAKE_BUILD_TYPE:      Release
-- CMAKE_INSTALL_PREFIX:  /my/home/directory/where/i/store/radium/Bundle-GNU
-- RADIUM_ENABLE_TESTING: ON
-- RADIUM_INSTALL_DOC:    ON
--   possible options: Debug Release RelWithDebInfo MinSizeRel
--   set with ` cmake -DCMAKE_BUILD_TYPE=Debug .. `
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /my/home/directory/where/i/store/radium/build
```

```
┌──────────────────┤│ radiumproject Project configuration │├────────────────────┐
│ Externals will be built with 40 core(s)                                       │
│ No CMAKE_BUILD_TYPE, using default CMAKE_BUILD_TYPE=Release                   │
│ USE_GOLD_LINKER                           OFF                                 │
│ Git Changeset: 5f9dab8f59a003420466c6ce3276d3b8be956112                       │
└───────────────────────────────────────────────────────────────────────────────┘
-- [Doc] Can build doc?                            YES
-- [Doc]   + PlantUML - for custom UML             YES 
-- [Doc]   + Graphviz/Dot - for generated graphs   YES 
-- [Sanitizers] Sanitizers:
-- [Sanitizers]   + ADDRESS_SANITIZER                     OFF
-- [Sanitizers]   + UB_SANITIZER                          OFF
-- [Sanitizers]   + THREAD_SANITIZER                      OFF
-- [Core] [addExternalFolder] process Core /my/home/directory/where/i/store/radium/external/Core
-- [Core] [External] Create temporary directory
-- [Core] [External] Configure cmake project
-- [Core] [External] Skip Core::external update (use RADIUM_SKIP_CORE_EXTERNAL to change behavior)
-- [Core] [addExternalFolder] end process Core /my/home/directory/where/i/store/radium/external/Core
-- [Core] Configuring library Core with standard settings
-- [IO] [addExternalFolder] process IO /my/home/directory/where/i/store/radium/external/IO
-- [IO] [External] Create temporary directory
-- [IO] [External] Configure cmake project with options -DRADIUM_IO_ASSIMP=OFF;-DRADIUM_IO_TINYPLY=ON
-- [IO] [External] Skip IO::external update (use RADIUM_SKIP_IO_EXTERNAL to change behavior)
-- [IO] [addExternalFolder] end process IO /my/home/directory/where/i/store/radium/external/IO
-- [IO] Configuring library IO with standard settings
-- [Engine] [addExternalFolder] process Engine /my/home/directory/where/i/store/radium/external/Engine
-- [Engine] [External] Create temporary directory
-- [Engine] [External] Configure cmake project
-- [Engine] [External] Skip Engine::external update (use RADIUM_SKIP_ENGINE_EXTERNAL to change behavior)
-- [Engine] [addExternalFolder] end process Engine /my/home/directory/where/i/store/radium/external/Engine
-- [Engine] Configuring library Engine with standard settings
-- [Engine] installing resources from /my/home/directory/where/i/store/radium/Shaders
-- [Engine] [installTargetResources] Linking resources directory /my/home/directory/where/i/store/radium/Shaders for target Engine into /my/home/directory/where/i/store/radium/build/src/Resources/Shaders
-- [Engine] [installTargetResources] Installing resources for target Engine into Resources/
-- [GuiBase] QT 5.15.1 found.
-- [GuiBase] Configuring library GuiBase with standard settings
-- [GuiBase] installing resources from Configs
-- [GuiBase] [installTargetResources] Linking resources directory /my/home/directory/where/i/store/radium/src/GuiBase/Configs for target GuiBase into /my/home/directory/where/i/store/radium/build/src/Resources/Configs
-- [GuiBase] [installTargetResources] Installing resources for target GuiBase into Resources/
-- [PluginBase] QT 5.15.1 found.
-- [PluginBase] Configuring library PluginBase with standard settings
-- [addMiscTargets] clang-tidy - static analysis              YES 
-- [addMiscTargets] cppcheck - static analysis                NO 
-- [addMiscTargets] clang-format - code formating             YES 
-- [Tests] [Sanitizers] Sanitizers:
-- [Tests] [Sanitizers]   + ADDRESS_SANITIZER                     OFF
-- [Tests] [Sanitizers]   + UB_SANITIZER                          OFF
-- [Tests] [Sanitizers]   + THREAD_SANITIZER                      OFF
-- [Tests] Already downloaded: https://github.com/catchorg/Catch2.git
-- [Tests] [configure_radium_app] Configuring application CoreExampleApp for being relocatable after installation.
-- [Tests] Installing HelloRadium into /my/home/directory/where/i/store/radium/Bundle-GNU
-- [Tests] [configure_radium_app] Configuring application HelloRadium for being relocatable after installation.
-- [Tests] [configure_radium_app] Deploying QT is not yet supported for application HelloRadium on Linux
-- [Tests] Installing SimpleSimulationApp into /my/home/directory/where/i/store/radium/Bundle-GNU
-- [Tests] [configure_radium_app] Configuring application SimpleSimulationApp for being relocatable after installation.
-- [Tests] [configure_radium_app] Deploying QT is not yet supported for application SimpleSimulationApp on Linux
-- [Tests] Installing DrawPrimitivesDemo into /my/home/directory/where/i/store/radium/Bundle-GNU
-- [Tests] [configure_radium_app] Configuring application DrawPrimitivesDemo for being relocatable after installation.
-- [Tests] [configure_radium_app] Deploying QT is not yet supported for application DrawPrimitivesDemo on Linux
-- [Tests] Installing SimpleAnimationApp into /my/home/directory/where/i/store/radium/Bundle-GNU
-- [Tests] [configure_radium_app] Configuring application SimpleAnimationApp for being relocatable after installation.
-- [Tests] [configure_radium_app] Deploying QT is not yet supported for application SimpleAnimationApp on Linux
-- [Tests] Installing plugin demo into /my/home/directory/where/i/store/radium/build/tests/ExamplePluginWithLib/Plugins-GNU
┌────────────────────┤│ Final overview for radiumproject │├─────────────────────┐
│ Version:               1.0.0 beta @ caravage                                  │
│ Install prefix:                                                               │
│   /my/home/directory/where/i/store/radium/Bundle-GNU                          │
│ Compiler:              /usr/bin/c++                                           │
│ CMAKE_BUILD_TYPE               Release                                        │
│   possible options: Debug Release RelWithDebInfo MinSizeRel                   │
│   set with ` cmake -DCMAKE_BUILD_TYPE=Debug .. `                              │
│ RADIUM_ENABLE_TESTING          ON                                             │
│ RADIUM_GENERATE_LIB_CORE       ON                                             │
│ RADIUM_GENERATE_LIB_ENGINE     ON                                             │
│ RADIUM_GENERATE_LIB_GUIBASE    ON                                             │
│ RADIUM_GENERATE_LIB_IO         ON                                             │
│ RADIUM_GENERATE_LIB_PLUGINBASE ON                                             │
│ RADIUM_GIT_UPDATE_SUBMODULE    ON                                             │
│ RADIUM_IO_ASSIMP               OFF                                            │
│ RADIUM_IO_TINYPLY              ON                                             │
│ RADIUM_IO_DEPRECATED           ON                                             │
│ RADIUM_SKIP_CORE_EXTERNAL      ON                                             │
│ RADIUM_SKIP_ENGINE_EXTERNAL    ON                                             │
│ RADIUM_SKIP_IO_EXTERNAL        ON                                             │
│ RADIUM_INSTALL_DOC             ON                                             │
│ RADIUM_UPDATE_VERSION          ON                                             │
│ RADIUM_QUIET                   OFF                                            │
└───────────────────────────────────────────────────────────────────────────────┘
-- Configuring done
-- Generating done
-- Build files have been written to: /my/home/directory/where/i/store/radium/build
```

### CODE REVIEW

**Comment by nmellado** [comment]
I like it.
Is the gold-linker option still relevant ?

**Comment by dlyr** [comment]
Well I don't have the history of this one ... I just worked on format not usefullness of the different steps ;)

**Comment by dlyr** [comment]
I'll give a try building, with empty useGoldLinker.cmake

**Comment by nmellado** [comment]
This is interesting because this message is posted only when the gold linker is available:

https://github.com/STORM-IRIT/Radium-Engine/blob/904ecaf4554303f255d3b826b24ef9cc87f8d90a/cmake/useGoldLinker.cmake#L3

That's good to keep it, but it would be better to print the message with the other options. Could you do that ?

**Comment by dlyr** [comment]
build works without gold.
actually I move the message out of the useGoldLinker.cmake to main CMakeLists.txt
the message print is now moved to the end, with other options.

**Review by nmellado — APPROVED** [review]

**Review by MathiasPaulin — APPROVED** [review]

**Pull request merged**
