### PR TITLE
Add new utility class for range loop reverse iteration

### PR DESCRIPTION
**Pull request by nmellado**

### CODE REVIEW

**Comment by louen** [comment]
Pretty cool stuff

**Comment by nmellado** [comment]
Useful let say ;)
All the credit goes to the stackoverflow guy.

I'm waiting for the positive review to accept this :D

**Comment by louen** [comment]
Hey, you wrote this code
And it is pretty,
But you could also
Make a unit test maybe ?

**Comment by nmellado** [comment]
I really hope these tests make you walk on air.

**Pull request merged**
