### PR TITLE
Fix manipulator exports

### PR DESCRIPTION
**Pull request by nmellado**
_Check if you branch history is PR compatible_
- Your branch need to be up to date with origin/master AND to have linear history (i.e. no merge commit).
- Update your git repository `git fetch origin` if origin is this remote
- Check with the script provided in `scripts/is-history-pr-compatible.sh`
- You must use clang-format style
_These checks are enforced by github workflow actions_
_Please refer to the corresponding log in case of failure_

_UPDATE the form below to describe your PR._

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by nmellado** [comment]
@dlyr @MathiasPaulin I am stuck with this fix.
The problem is the following (with MSVC only): 
 - in the current version, the static member `KeyMappingManageable<T>::m_keyMappingContext` is not exported for the specialized classes (e.g. `TrackballCameraManipulator`, defined as `public KeyMappingManageable<TrackballCameraManipulator>`) https://github.com/STORM-IRIT/Radium-Engine/blob/fd9e7909fbe48ed62b8ba2926782071167107f59/src/GuiBase/Viewer/TrackballCameraManipulator.hpp#L10
To demonstrate that this is a problem, I have added a simple application that tries to extend `TrackballCameraManipulator`, and I get a link error (`unresolved external symbol`) when compiling it: https://github.com/STORM-IRIT/Radium-Engine/pull/671/checks?check_run_id=1784225564#step:11:6283 
 - In c167050ad8c5f2f3481d201fac74a5eaf812d576 i have tried explicit specialization. Didn't work: `error C2908: explicit specialization; 'Ra::Gui::KeyMappingManager::Context Ra::Gui::KeyMappingManageable<Ra::Gui::FlightCameraManipulator>::m_keyMappingContext' has already been instantiated`. https://github.com/STORM-IRIT/Radium-Engine/runs/1783465751#step:11:192
 - In 8494618e939350525e1fb65c30f0fbdf4dce88bd I try with explicit instantiation and specialization. Didn't work: https://github.com/STORM-IRIT/Radium-Engine/runs/1783658352#step:11:194

I you have any idea on how to fix it. I've looked online but couldn't figure it out.
Note that because of this issue, Radium-Release is currently broken on Windows: 
https://github.com/STORM-IRIT/Radium-Releases/runs/1777262644?check_suite_focus=true

**Comment by MathiasPaulin** [comment]
> I you have any idea on how to fix it. I've looked online but couldn't figure it out.
> Note that because of this issue, Radium-Release is currently broken on Windows:
> https://github.com/STORM-IRIT/Radium-Releases/runs/1777262644?check_suite_focus=true

I'll give a look as soon as possible on this.

**Comment by dlyr** [comment]
Not sure, but do the dllexport can be added to the templated class KeyMappingManageable ... 
first google search that seems to corresponds https://dreamdota.com/dll-exporting-a-crtp-base/
https://stackoverflow.com/questions/7848865/dll-exporting-static-members-of-template-base-class
https://forums.codeguru.com/showthread.php?108090-Exporting-Template-Classes-with-Static-Member-Variables-from-DLL

Not sure how to handle it perfectly.

**Review by dlyr — DISMISSED** [review]
Fine for me (still not fan of the KMManageable, maybe an alias as KeyMapping, ok MyKeyMapping can be clearer).

Could you update the doc 
https://github.com/STORM-IRIT/Radium-Engine/blob/master/doc/developer/keymapping.md

And even better: add unit test ;)

**Comment by nmellado** [comment]
ok for the doc (it was planned)
For the unit tests, I have no idea how to do it, that's why I added the application.

**Review by MathiasPaulin — COMMENTED** [review]
Somme suggestions

**Comment by dlyr** [comment]
I'll give a try for unittest, but we can accept the PR before ;)

**Comment by nmellado** [comment]
Ok thanks.
I have integrated suggestion by Mathias (locally), and I'll push the doc soon

**Review by MathiasPaulin — APPROVED** [review]

**Pull request merged**
