### PR TITLE
Fix picking on Windows ;

### PR DESCRIPTION
**Pull request by hoshiryu**
Apparently, issue #295 is due to the "discard" command, at least on Windows.

### CODE REVIEW

**Comment by hoshiryu** [comment]
@MathiasPaulin can you check it's working on mac please?
By the way, should we add a PICKING pass to the RenderTechnique so that we don't have to split the renderqueue w.r.t. the render primitive? 
This would put extra, related stuff in the render method though, like is the RO "pickable", set the RO id as uniform and specific transform computations for UI ROs

**Comment by hoshiryu** [comment]
checked on windows

**Comment by MathiasPaulin** [comment]
checked on macos.
concerning the remark by @hoshiryu, I agree that picking must be refactored, but this must be done deeply and wrt the rendering process. I think that it is something that go over the current PR.
So, first, merge this bug-fix, then, open a new feature request for picking refactoring.

**Comment by nmellado** [comment]
I do agree with @MathiasPaulin (see Contributing Guidelines).

Btw, it’s now time to work on Radium V1 RC, starting by modifying the filesystem and namespaces, which will break the API and thus need to be done before any other change.

**Pull request merged**
