### PR TITLE
Delete buffers, should fix #438

### LINKED ISSUE #437: Plugin MeshPaint is buggy
The MeshPaint plugin has some behavior issues.
When disabling color painting and reactivating it, the mesh is all black with `per-vertex` diffuse color material.
This might be due to missing attribute removal on painting disabling.

### PR DESCRIPTION
**Pull request by dlyr**
Replacement proposal for #438, but I'm not sure to catch all the issues, so please check ;)

I also reformat all code (in a separate commit), according to last script version.
So please check by commit to not get disturbed by the numerous changes.

---------------------- Update pull request manifest -----------------------
UPDATE the form below to describe your PR.

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix #437 

* **What is the current behavior?** (You can also link to an open issue here)
When de-activating mesh paint and re-activating it on a mesh with no previous `per-vertex` colors, the mesh ends up all black and painting colors does not work.
Actually this is due to the fact that, when de-activating colors painting, the colors are set back to what they were before painting, which in this case is `none`.
Thus when re-activating painting, since the mesh has the color attribute, the plugin just copies it and no validity check is done.
Hence when painting the colors, colors are set in an empty container (this should crash but somehow does not).

* **What is the new behavior (if this is a feature change)?**
- On color painting activation, the plugin request the addition of a color attribute to the mesh.
If there is only one, this one is selected as the `to be painted` and previous colors are saved.
Otherwise, a new one is created and filled with a default color.
- On color painting de-activation, the colors are set to what they were beforehand, i.e. either the saved ones or the created attribute is removed.

### CODE REVIEW

**Comment by hoshiryu** [comment]
There is an issue with Travis-CI: the compilation is marked as `passed` while there was a compilation error:
```
/home/travis/build/STORM-IRIT/Radium-Engine/Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.cpp: In member function ‘Scalar MeshFeatureTrackingPlugin::MeshFeatureTrackingComponent::getFeatureScale() const’:
/home/travis/build/STORM-IRIT/Radium-Engine/Plugins/MeshFeatureTracking/src/MeshFeatureTrackingComponent.cpp:587:18: error: ‘using element_type = class Ra::Engine::RenderObject {aka class Ra::Engine::RenderObject}’ has no member named ‘computeAabb’
     { return ro->computeAabb().sizes().norm() / 500; }
                  ^~~~~~~~~~~
```

**Comment by hoshiryu** [comment]
Regarding the code for paint activation, it seems the code should be changed, as proposed in #438 :
```[cpp]
if ( m_currentColorAttribHdl.idx().isInvalid() )
{
    m_baseColors.clear();
    m_isBaseColorValid = false;
    triangleMesh.colorize( Ra::Core::Utils::Color::Skin() );
    m_currentColorAttribHdl =
        triangleMesh.getAttribHandle<Ra::Core::Vector4>( colAttribName );
    m_mesh->setDirty( Ra::Engine::Mesh::VERTEX_COLOR, true );
}
else
{
    m_isBaseColorValid = true;

    m_baseColors = triangleMesh.getAttrib( m_currentColorAttribHdl ).data(); // copy
}
```
should be simplified as:
```[cpp]
m_baseColors  = triangleMesh.getAttrib( m_currentColorAttribHdl ).data();
m_isBaseColorValid = m_baseColors.size() != 0;
if (  !m_isBaseColorValid )
{
    triangleMesh.colorize( Ra::Core::Utils::Color::Skin() );
    m_mesh->setDirty( Ra::Engine::Mesh::VERTEX_COLOR, true );
}
```
where the first line creates the attribute if it doesn't exist, while clears the colors otherwise.

**Comment by dlyr** [comment]
Well, reading your proposal, I think it is based on the fact that addAttrib do not allocate space to store the attribute, which might change.
I prefer the explicit version

**Comment by hoshiryu** [comment]
fair

**Pull request merged**
