### PR TITLE
Guideline checks for history and format.

### PR DESCRIPTION
**Pull request by dlyr**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
A script to check one's branch history before PR.
This script is check with github workflow checks.
It also add a script to check format and a way to make github apply formatting.

* **What is the current behavior?** (You can also link to an open issue here)
We use only rebase PR, and looses the coherency of feature addition.

* **What is the new behavior (if this is a feature change)?**
Now we want to use merge commit, but to keep a nearly linear history, the branch that is in PR must have linear history and be up to date with master.

The PR template is updated, and a scirpt (bash) is given.

### CODE REVIEW

**Comment by nmellado** [comment]
We can have add a test using Github actions, which will prevent PRs to be merged if this script fails. I can do it later if you want.

**Comment by dlyr** [comment]
I can try to do it, but not sure which action is best for that. If you can point me where I can find the relevant approach, I can have a look.

**Comment by dlyr** [comment]
I saw there is also action for clang-format, but not sure what is the best and how to set it up.

**Comment by dlyr** [comment]
Github action added, I also checked clang format ... when ok I could push a commit that reformat invalid files

**Comment by dlyr** [comment]
I have added required check for history, might "blcok" other PR, but we can revert the config if needed.

**Comment by dlyr** [comment]
I have another check in test to format and commit changes automatically, so that if you clang format version differ you don't have to mind.

**Comment by nmellado** [comment]
@dlyr you will need this commit to get the CI working again, catch2 master is broken
https://github.com/STORM-IRIT/Radium-Engine/pull/579/commits/cd3ca2b1cfa0258aa5a65ab62f48b73302f08a6b

**Comment by dlyr** [comment]
See [here](https://github.com/dlyr/Radium-Engine/pulls) for example feedback on failure

**Comment by nmellado** [comment]
All the other PR will have to be updated as this one changes the format of all the files

**Comment by dlyr** [comment]
see [here](https://github.com/STORM-IRIT/Radium-Engine/wiki/Rebase-on-reformatted-master) for help on rebase onto reformated master.

**Pull request merged**
