### PR TITLE
Update CI, clean workflow regarding version bump.

### PR DESCRIPTION
**Pull request by dlyr**
Try to make ci cleaner, and work with version bump before any other ci jobs on master and release candidate pushes.

### CODE REVIEW

**Review by MathiasPaulin — APPROVED** [review]
I do not understand (nor will try to understand) how everything is working but as this is needed and if it works effectually, I approve.

**Comment by dlyr** [comment]
Well I'm not sure it will work out of the box, the firsts tests seems ok, but I haven't tested deploy doc nor notify since it's meant to be done on rc or master only.
Do you think I need to add some doc ? On my side I think the documentation is github action documentation (on how each workflow work and how they are related ... there is no big surprise nor hack)
But I can write a small introduction in each workflow file giving its objective and key concept.

**Comment by nmellado** [comment]
> Do you think I need to add some doc ? On my side I think the documentation is github action documentation (on how each workflow work and how they are related ... there is no big surprise nor hack)
But I can write a small introduction in each workflow file giving its objective and key concept.

Yes that would be great to have a kind of short doc at the beginning of the CI files, just to explain what is done, and who triggers this scripts, and what this script triggers.

**Comment by MathiasPaulin** [comment]
> On my side I think the documentation is github action documentation (on how each workflow work and how they are related ... there is no big surprise nor hack)

I agree, no need to add doc

> But I can write a small introduction in each workflow file giving its objective and key concept.

could be helpful but even for people who know only  a few about github action, the code is clear.

**Review by nmellado — APPROVED** [review]

**Comment by dlyr** [comment]
Now we can hope that everything will work when merged ;)

**Comment by nmellado** [comment]
Yes.
Feel free to merge when you have some time available to fix any problem...

**Pull request merged**
