### PR TITLE
Improve buildchain

### PR DESCRIPTION
**Pull request by nmellado**
This PR aims at cleaning the buildchain, by:
 - add missing CMake parameters for submodules compilation
 - enable exceptions to improve compatibility with submodules
 - Fix warnings due to buildchain issues
 - Force use of local glm when compiling globjects

### CODE REVIEW

**Comment by nmellado** [comment]
Fixes #287.

**Comment by nmellado** [comment]
PR ready for review

**Comment by MathiasPaulin** [comment]
Seems OK for me except that there is still the MacOsX @rpath bug when executing applications in the build tree ... I've try some fix, such as the one explained [here](https://cmake.org/Wiki/CMake_RPATH_handling) but with no success. As recompiling the whole takes loooong time, I'll continue tomorrow.

**Comment by nmellado** [comment]
Right, I will try to add a fix tomorrow.

**Comment by nmellado** [comment]
@MathiasPaulin can you try again with my tentative fix ?

**Comment by MathiasPaulin** [comment]
This fix does not work. When executing an application (main-app or helloRadium), I get the following message : 
```
dyld: Library not loaded: @rpath/libglbinding.3.dylib
  Referenced from: /Users/mathias/Professionnel/SVN-IRIT-paulin/paulin/Developpement/Radium/Radium-Engine/Bundle-GNU/Release/bin/main-app
  Reason: image not found
``` 

When lookin libs that are linked against the executable, I get : 

```
$otool -L ./main-app
./main-app:
        @rpath/libradiumGuiBase.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/libglbinding.3.dylib (compatibility version 3.0.0, current version 3.0.0)
        /Users/mathias/Professionnel/SVN-IRIT-paulin/paulin/Developpement/Radium/Radium-Engine/Bundle-GNU/3rdPartyLibraries/lib/libassimp.3.dylib (compatibility version 3.0.0, current version 3.3.1)
        @rpath/libradiumIO.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/libradiumEngine.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/libradiumCore.dylib (compatibility version 0.0.0, current version 0.0.0)
        @rpath/libOpenMeshCore.7.0.dylib (compatibility version 7.0.0, current version 7.0.0)
        @rpath/QtOpenGL.framework/Versions/5/QtOpenGL (compatibility version 5.9.0, current version 5.9.1)
        @rpath/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.9.0, current version 5.9.1)
        @rpath/QtGui.framework/Versions/5/QtGui (compatibility version 5.9.0, current version 5.9.1)
        /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
        @rpath/libglobjects.2.dylib (compatibility version 2.0.0, current version 2.0.0)
        @rpath/QtXml.framework/Versions/5/QtXml (compatibility version 5.9.0, current version 5.9.1)
        @rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.9.0, current version 5.9.1)
        /opt/local/lib/libgcc/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.24.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
        /opt/local/lib/libgcc/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
As all is fine for assimp, I'll lok on the differences in assimp's cmake and build chain to understand what is wrong with others ...

**Comment by nmellado** [comment]
Ok thanks for the report, this definitively helps !

**Comment by nmellado** [comment]
Compilation is broken with latest VS. 
Do not merge the PR.

**Pull request merged**
