### PR TITLE
Workflow badges

### PR DESCRIPTION
**Pull request by dlyr**
This pull request add new badges according to the new CI with github actions.
Before merge, we need to remove pull_request selection in push_master.yml workflow.
The resulting badges are shown gere https://github.com/STORM-IRIT/Radium-Engine/tree/workflow-badges

### CODE REVIEW

**Comment by nmellado** [comment]
You can use this action to get badges from the different OS: https://github.com/marketplace/actions/bring-your-own-badge

**Comment by dlyr** [comment]
seems tricky

**Comment by dlyr** [comment]
**CHECK LINEAR HISTORY FAIL**

Please rebase on current up to date master,
without merge commits (e.g. you can squash them).

**Comment by dlyr** [comment]
I think I got it ... let's wait ...

**Comment by nmellado** [comment]
Hum I dont like the fact that we need to recompile everything again. It takes time and it is not really green...
Why do not modify the existing checks to add a post-build badge generation ?

**Comment by dlyr** [comment]
Switch to [dynamic badges](https://github.com/marketplace/actions/dynamic-badges)
need to follow setup for STORM-IRIT user as 


1. Head over to gist.github.com and create a new gist. You will need the ID of the gist (this is the long alphanumerical part of its URL) later.
2. Navigate to github.com/settings/tokens and create a new token with the gist scope.
3. Go to the Secrets page of the settings of your repository and add this token as a new secret. You can give it any name, for example GIST_SECRET.


and change `gistID: <gist-ID>` in workflow files.

**Comment by dlyr** [comment]
examples badges here
https://github.com/dlyr/Radium-Engine

**Comment by nmellado** [comment]
> Switch to [dynamic badges](https://github.com/marketplace/actions/dynamic-badges)
> need to follow setup for STORM-IRIT user as
> 
> 1. Head over to gist.github.com and create a new gist. You will need the ID of the gist (this is the long alphanumerical part of its URL) later.
> 2. Navigate to github.com/settings/tokens and create a new token with the gist scope.
> 3. Go to the Secrets page of the settings of your repository and add this token as a new secret. You can give it any name, for example GIST_SECRET.
> 
> and change `gistID: <gist-ID>` in workflow files.

The

**Review by nmellado — APPROVED** [review]

**Pull request merged**
