### PR TITLE
Fix engine namespace

### PR DESCRIPTION
**Pull request by MathiasPaulin**
Following PR #642 and when updating an external application, I found two concerns : 
  The class `ShaderProgram` was predeclared in the wrong namespace in the file `Mesh.hpp` 
    --> Fix the predeclaration
  The class `ViewingParameters` is declared in the namespace `Data` but the file `ViewingParameters.hpp` is in the directory `Rendering` 
    --> The file is moved in this PR

The 2 commits of this PR correspond to the given fixes.

### CODE REVIEW

**Comment by dlyr** [comment]
I have added more fixes (since I was wierd the program compiles with this predeclaration, there might be a unneeded include, I saw also an header include at the end of another ... don't know what happens, either my script or clion ...)

**Review by dlyr — APPROVED** [review]

**Comment by dlyr** [comment]
When merged, I'll update the automation script.

**Comment by MathiasPaulin** [comment]
> I have added more fixes (since I was wierd the program compiles with this predeclaration, there might be a unneeded include, I saw also an header include at the end of another ... don't know what happens, either my script or clion ...)

You're welcome. This was detected by clang-tidy which tell about ambiguities. I found also a lot of unneeded includes but wants to keep the PR small. I'll do another one that removes all these unneeded includes in a few days (and will run cpp-check also).

**Comment by dlyr** [comment]
perfect, I'm fine with merge.

**Pull request merged**
