### PR TITLE
Fix dirty bits in Mesh ;

### PR DESCRIPTION
**Pull request by hoshiryu**
* **Please check if the PR fulfills these requirements**
- [ ] Is the Pull-Request done against the right branch:
  - `master`: for hotfixes not impacting the API
  - `master-v1`: for changes related to the Radium Stable Release V1.
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix `Engine::Mesh::m_dataDirty` when loading `TriangleMesh`

* **What is the current behavior?** (You can also link to an open issue here)
When loading a `Core::TriangleMesh` into an `Engine::Mesh`, the dirty bits for the attributes are not set, thus the attributes are not loaded on the GPU.

* **What is the new behavior (if this is a feature change)?**
The dirty bits are now set for all data.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by hoshiryu** [comment]
What about `Mesh::updateMeshGeometry()` and `Mesh::loadGeometry( vertices, indices)`?

**Comment by nmellado** [comment]
It is true that `updateMeshGeometry` might lead to inconsistent state. On the other hand it doesn't seems to be used anywhere. Shall we remove it ?
`loadGeometry` sets the dirty flags, what's wrong with it ?
The non-const version of `getData` is maybe too intrusive, + I cannot find any use in the main project. Shall we also remove it ?

**Comment by hoshiryu** [comment]
I'm ok to remove these. @dlyr @MathiasPaulin is it ok for you too?

**Comment by hoshiryu** [comment]
Regarding `loadGeometry( vertices, indice )`, what shall we do about the attributes?

**Comment by nmellado** [comment]
In `loadGeometry`, there is basically two options: either the vertices are updated (ie. there is not vertex addition or removal), or the vertex list is modified.
In the second case, it is clear that attributes must be invalidated. In the first case however, we don’t know, it can be an update of the geometry, or a completely new geometry with the same number of vertices.

Considering this, we first need to confirm we really need that method. If yes, in which case ? With all these information we will decide what to do.
 Personally I don’t like this kind of method as it make break the data integrity. But I might be wrong, so I’m open to discussions.

**Comment by hoshiryu** [comment]
I removed `Mesh::updateGeometry` and the non-const versions of `Mesh::getData`.
Regarding`Mesh::loadGeometry( vertices, indices )` I kept it since it is used for non-`RM_TRIANGLES` meshes (e.g. lines, points, strips, ...).

**Pull request merged**
