### PR TITLE
Fix numeric cast in VolumeLoader

### PR DESCRIPTION
**Pull request by nmellado**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

Be aware that the PR request cannot be accepted if it doesn't pass the Continuous Integration tests.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
Compilation of `VolumeLoader` fails on some platforms due to missing cast for Eigen Scalar type.
https://github.com/STORM-IRIT/Radium-Engine/runs/4844992814?check_suite_focus=true#step:15:3986

* **What is the new behavior (if this is a feature change)?**
Cast has been added

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Review by dlyr — APPROVED** [review]

**Comment by nmellado** [comment]
Sorry for the noise, ready for review now.

**Review by dlyr — APPROVED** [review]
How did this pass continuous integration in the first time ?

**Comment by nmellado** [comment]
To be honest I do not understand.
As you can see here, only half of the compilation units fail:
https://github.com/STORM-IRIT/Radium-Engine/actions/runs/1709474823

**Comment by dlyr** [comment]
Got it, during PR, CI only test Scalar = float, while after accepting, CI tests also Scalar = double, typically to detect this kind of issue.

**Comment by nmellado** [comment]
I see, makes sense.

**Review by MathiasPaulin — APPROVED** [review]

**Pull request merged**
