### PR TITLE
Test doc

### PR DESCRIPTION
**Pull request by dlyr**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature: build and deploy documentation for both master and release candidate.

* **What is the current behavior?** (You can also link to an open issue here)
Doc is only build for master branch.

### CODE REVIEW

**Review by nmellado — APPROVED** [review]

**Comment by dlyr** [comment]
Before acceptance, we need to update target branches.

**Comment by nmellado** [comment]
You mean master and release_candidate ?

**Comment by nmellado** [comment]
Oh yes, I see

**Comment by dlyr** [comment]
One solution is to pass this branch directly on master, then rebase release-candidate on new master ... hence we will have doc updated, without having other release-candidate modification.

**Comment by nmellado** [comment]
Fine for me, could you please rebase on top of `master` ?

**Comment by nmellado** [comment]
@dlyr the CI will not be launched. I guess you can merge anyway and rebase `release_candidate` ?

**Comment by dlyr** [comment]
Sure let's try to break master ;)

**Pull request merged**
